- docker-compose.dev.yml
Criei o arquivo `docker-compose.dev.yml` para facilitar para os novos desenvolvedores que queiram contribuir com o projeto. O arquivo compose já cria o container da API e do banco de dados Postgres junto.
Para rodar ele, precisa especificar o nome do arquivo: `docker compose -f docker-compose.dev.yml up -d`
> Adicionar docker compose para ambiente de DEV

- src/shelter/shelter.service.ts
- Adicionada condição na query para tornar a busca do abrigo case insensitive
Ao buscar pelo termo "esperança" nada foi encontrado
Mas buscando por "Esperança" o resultado é retornado
> Tornando a busca de abrigos por endereço ou nome case insensitive

- src/shelter/shelter.service.ts
- Esse PR irá:
-  [🐛 Remove 'UnderControl' supplies from shelter queries](https://github.com/SOS-RS/backend/commit/5b9c29538e90b36de96e8addd6cee13a10112863)
- Basicamente, remove os itens 'não preciso' da home/lobby do shelter.
> fix: Remove 'UnderControl' supplies from shelter queries

- src/shelter/types.ts
Ao tentar cadastrar um abrigo é apresentado um erro de validação
1. Entrar no painel admin
2. [Logue no sistema](http://127.0.0.1:5173/entrar) `/entrar`
3. [Ir em cadastrar abrigo](http://127.0.0.1:5173/abrigo/cadastrar) `abrigo/cadastrar`
4. Preencha os dados necessários
5. Clique em cadastrar
6. Deve aparecer um `ZodError`
Foi notado que no schema o default para `verified` está setado para false mas o problema está no zod para criação, ele verifica o campo(é necessário enviar o `verified`).
Portanto a solução foi deixar o omit de verified na criação.
> [develop] ZodError no cadastro do abrigo

- prisma/migrations/20240509235041_/migration.sql
- prisma/schema.prisma
- src/shelter-supply/shelter-supply.service.ts
- src/shelter-supply/types.ts
- src/shelter/shelter.service.ts
Esse PR faz parte da task: [[Full] Adicionar quantidade nos itens](https://trello.com/c/X7lLVvkk/9-full-adicionar-quantidade-nos-itens).
Basicamente adicionei na tabela de **shelter_supplies** a coluna númerica **quantity**  que é nullable por padrão. Na rota **/shelter/supplies** é possivel enviar essa propriedade ou não, caso seja enviado ela precisa ser maior que 0.
As rotas que pegam registros da tabela **shelter_supplies** devolveram essa propriedade junto.
> Adicionado propriedade de quantidade de suprimentos nos abrigos

- Dockerfile
- docker-compose.dev.yml
- tsconfig.json
**O QUE CONSTA NO PR:**
- Remove variáveis hardcoded no docker compose. Agora o .env é a única fonte de informações e se precisar alterar será em um único lugar.
- Adiciona configuração de _watchOptions_ em tsconfig.json que permite que a flag --watch funcione rodando com Docker. Agora qualquer modificação no código será automaticamente refletida sem a necessidade de descer o container e subir novamente.
- A versão do node considerada no docker compose foi atualizada também no Docker file para evitar conflitos.
**EVIDÊNCIAS DE FUNCIONAMENTO:**
Logs:
**COMO TESTAR**
Rode o servidor normalmente com o docker compose e acesse algum endpoint (ex.: http://localhost:4000/shelters). Experimente trocar a mensagem da resposta padrão de "Successfully get shelters" para alguma outra para ver a …
> Quality of life: implement some quality of life updates reg Docker

- src/shelter-supply/shelter-supply.service.ts
Este Pull Request aborda uma inconsistência no mecanismo de atualização para shelter_supplies em lote a partir do endpoint **PUT shelter/supplies/<shelterId>/many** e seus correspondentes shelters.
As atualizações no **shelter_supply.priority** deste endpoint não estavam refletiam no **shelter.priority_sum**, que é crucial para a ordenação dos abrigos por prioridade decrescente. Este descuido poderia levar a ordenações incorretas e agora foi corrigido.
1. Atualizado o método **ShelterSupplyService.updateMany** para garantir que qualquer alteração em **shelter_supply.priority** também acione uma atualização no **shelter.priority_sum** correspondente.
2. Adicionada uma transação para garantir que as atualizações em shelter_supplies e shelters sejam atômicas, evitando atualizações parciais. …
> hotfix: Correção da Atualização Inconsistente de Prioridade em Shelter Supplies

- src/decorators/UserDecorator/index.ts
- src/decorators/UserDecorator/user.decorator.ts
- src/guards/apply-user.guard.ts
- src/guards/utils.ts
- src/shelter/shelter.controller.ts
- src/shelter/shelter.service.ts
- src/shelter/types/search.types.ts
É necessário ocultar o dado de contato(telefone) para o público em geral e restringir para apenas usuários(`STAFF` e `USER`) para controlar melhor quem visualiza e deixar apenas para pessoal capacitado(registrado).
Como as guards atuais no `controller`(como `@UseGuards(UserGuard)`) restrigem totalmente o acesso a aquela rota para usuários registrados foi preciso
1. Fazer um decorator(para interceptar a request) para pegar o contexto e retornar o usuário(caso tenha)
2. Fazer uma guard para repassar o usuário para o controller
3. No controller pegar o usuário e repassar para o service
4. ~Então passar para uma função para verificar se o usuário(caso esteja logado) seja um dos permitidos(no momento todos)~ Basta verificar se um usuário é passado no guards(verificar se recebe do contexto de …
> Somente exibir campo de Contato quando logado(staff ou user)

- src/shelter/ShelterSearch.ts
- src/shelter/types/search.types.ts
- src/utils/utils.ts
Este PR:
- Adiciona filtro por raio na busca de abrigos (se lat/long forem informados nos query params da rota GET /shelters)
> feat: add shelter filter by geolocation radius

- src/shelter/ShelterSearch.ts
Ajustado o filtro para lidar com abrigos com informações de capacidade e lotação zeradas.
https://github.com/SOS-RS/frontend/issues/146
> fix: Correção da issue #146 do frontend.

- src/shelter/shelter.service.ts
- src/users/users.controller.ts
**O que?**
Removido as cidades nulas da lista de cidades retornada pelo endpoint GET shelter/cities.
**Por que?**
As cidades estavam vindo com o nome default de "Cidade não informada" quando ela possuia com campo city NULO no banco de dados. E esse comportamento estava fazendo aparecer no select do frontend inúmeras "cidade não informada". Quando usado uma cidade cujo nome era "Cidade não informada" no filtro e buscado na api, nao era retornado nenhum resultado, sendo que o comportamento esperado era não buscar por cidade específica já que a cidade não foi informada.
**Como?**
Adicionado uma clausula Where no filtro de cidades onde ele busca apenas os registros que possuem a coluna city como NOT NULL.
> fix: city filter

- .github/workflows/dev.yml
- .github/workflows/staging.yml
- prisma/migrations/20240516212629_/migration.sql
- prisma/schema.prisma
- src/app.module.ts
- src/partners/partners.controller.ts
- src/partners/partners.service.ts
- src/partners/types.ts
- src/supporters/supporters.controller.spec.ts
- src/supporters/supporters.controller.ts
- src/supporters/supporters.module.ts
- src/supporters/supporters.service.spec.ts
- src/supporters/supporters.service.ts
- src/supporters/types.ts
- Added endpoint to create and get all supporters (protected by admin rule)
- added endpoint to create partner (protected by admin rule)
> Feat: added supporters module and create partner endpoint

- README.md
Coloquei o que é necessário pra rodar a app, incluindo o banco, que estava faltando, e também como contribuir de volta.
> Update readme with run instructions

- src/partners/partners.controller.ts
- Adiciona o status code correto para criação de um novo recurso (partner)
** Verificar se o frontend utiliza validação do status ao chamar esse endpoint.
Source:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201
> fix: use correct status code(201) when create new entry on database

- src/partners/partners.controller.spec.ts
- src/partners/partners.service.spec.ts
- Melhora a cobertura de testes para a entidade `Partner`
> test: cover getMany and create for partners entity

- src/sessions/sessions.controller.spec.ts
- src/sessions/sessions.service.spec.ts
- Coverage the whole session use case
> test: cover the whole session controler and service use cases

- .github/workflows/deploy.yml
- .github/workflows/dev.yml
- .github/workflows/staging.yml
Com esse filtro evitamos que os workflows rodem nos forks.
> Não publicar em forks

- src/interceptors/interceptors/shelter-supply-history/shelter-supply-history.interceptor.ts
- src/interceptors/interceptors/shelter-supply-history/utils.ts
- src/prisma/prisma.service.ts
- src/shelter/shelter.service.ts
- src/shelter/types/types.ts
- Adicionado o decaimento das prioridades dos suprimentos para incentivar o usuário a atualizar os dados e para evitar dados desatualizados na base.
Foi utilizado os seguintes critérios:
- Caso o suprimento seja de prioridade `Urgent` (máxima) e não é atualizado a mais de 12 horas, ele é atualizado para o status de `Needing`. 
- Caso o suprimento seja de prioridade `Needing` ou `Remaining` e não é atualizado a mais de 48 horas, sua prioridade é atualizada para sob controle.
Além disso é salvo todos os logs do shelter supplies conforme já implementado nos endpoints de update.
--
Foi escolhido a estratégia de aproveitar o retorno da lista de abrigo e de abrigos únicos para obter a lista de suprimentos ao invés de rodar um schedule que sempre percorre inteiramente o banco de dados. Dessa …
> feat: added decay shelter supply behaviour

- src/shelter/ShelterSearch.ts
- src/shelter/types/search.types.ts
Conforme solicitado na issue [#257](https://github.com/SOS-RS/frontend/issues/257) foi removido o limite no retorno dos supplies de abrigo.
PR do Frontend: https://github.com/SOS-RS/frontend/pull/249
> Update - removendo limite de supplies na listagem de abrigos

- .env.test
- .github/workflows/ci.yml
- package-lock.json
- package.json
Adicionei o serviço de pg no build, um script de pre pra rodar as migrations, e retirei o npx do run delas.
> Run e2e tests on build
